2018-02-13 01:14:49 database: wrong user or password; user: "SA"
org.h2.message.DbException: Wrong user name or password [28000-195]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.openSession(Engine.java:104)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.server.web.WebServer.getConnection(WebServer.java:735)
	at org.h2.server.web.WebApp.login(WebApp.java:947)
	at org.h2.server.web.WebApp.process(WebApp.java:210)
	at org.h2.server.web.WebApp.processRequest(WebApp.java:169)
	at org.h2.server.web.WebThread.process(WebThread.java:133)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 19 more
2018-02-13 01:17:12 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FK_ALLERGENE__CATEGORIA_ID_IDX"; SQL statement:
CREATE TABLE vg_allergene (
  id char(36) NOT NULL,
  id_categoria char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  nome varchar(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY UNIQUE_allergene_nome (nome),
  KEY fk_allergene__categoria_id_idx (id_categoria),
  CONSTRAINT fk_allergene__categoria_id FOREIGN KEY (id_categoria) REFERENCES vg_categoria (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4161)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4004)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6102)
	at org.h2.command.Parser.parseCreate(Parser.java:4343)
	at org.h2.command.Parser.parsePrepared(Parser.java:365)
	at org.h2.command.Parser.parse(Parser.java:320)
	at org.h2.command.Parser.parse(Parser.java:292)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2018-02-13 01:23:49 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "PRIMARY"; SQL statement:
CREATE TABLE vg_allergene (
  id char(36) NOT NULL,
  id_categoria char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  nome varchar(45) NOT NULL,
  vg_allergene_pk PRIMARY KEY (id),
  vg_allergene_unique (nome),
  fk1 FOREIGN KEY ( id_categoria) REFERENCES vg_categoria (id) ON DELETE NO ACTION ON UPDATE NO ACTION  
) [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4161)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4004)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6102)
	at org.h2.command.Parser.parseCreate(Parser.java:4343)
	at org.h2.command.Parser.parsePrepared(Parser.java:365)
	at org.h2.command.Parser.parse(Parser.java:320)
	at org.h2.command.Parser.parse(Parser.java:292)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2018-02-13 01:24:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "("; SQL statement:
CREATE TABLE vg_allergene (
  id char(36) NOT NULL,
  id_categoria char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  nome varchar(45) NOT NULL,
  PRIMARY KEY (id),
  vg_allergene_unique (nome),
  fk1 FOREIGN KEY ( id_categoria) REFERENCES vg_categoria (id) ON DELETE NO ACTION ON UPDATE NO ACTION  
) [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4161)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4004)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6102)
	at org.h2.command.Parser.parseCreate(Parser.java:4343)
	at org.h2.command.Parser.parsePrepared(Parser.java:365)
	at org.h2.command.Parser.parse(Parser.java:320)
	at org.h2.command.Parser.parse(Parser.java:292)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2018-02-13 01:25:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "UNIQUE"; SQL statement:
CREATE TABLE vg_allergene (
  id char(36) NOT NULL,
  id_categoria char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  nome varchar(45) NOT NULL,
  PRIMARY KEY (id),
  vg_allergene_unique UNIQUE (nome),
  fk1 FOREIGN KEY ( id_categoria) REFERENCES vg_categoria (id) ON DELETE NO ACTION ON UPDATE NO ACTION  
) [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4161)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4004)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6102)
	at org.h2.command.Parser.parseCreate(Parser.java:4343)
	at org.h2.command.Parser.parsePrepared(Parser.java:365)
	at org.h2.command.Parser.parse(Parser.java:320)
	at org.h2.command.Parser.parse(Parser.java:292)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
2018-02-13 01:25:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "FOREIGN"; SQL statement:
CREATE TABLE vg_allergene (
  id char(36) NOT NULL,
  id_categoria char(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
  nome varchar(45) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (nome),
  fk1 FOREIGN KEY ( id_categoria) REFERENCES vg_categoria (id) ON DELETE NO ACTION ON UPDATE NO ACTION  
) [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:4161)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:4004)
	at org.h2.command.Parser.parseCreateTable(Parser.java:6102)
	at org.h2.command.Parser.parseCreate(Parser.java:4343)
	at org.h2.command.Parser.parsePrepared(Parser.java:365)
	at org.h2.command.Parser.parse(Parser.java:320)
	at org.h2.command.Parser.parse(Parser.java:292)
	at org.h2.command.Parser.prepareCommand(Parser.java:257)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:165)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1380)
	at org.h2.server.web.WebApp.query(WebApp.java:1053)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1015)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1002)
	at org.h2.server.web.WebThread.process(WebThread.java:164)
	at org.h2.server.web.WebThread.run(WebThread.java:89)
	at java.lang.Thread.run(Unknown Source)
